FROM eclipse-temurin:17-jdk

WORKDIR /app

COPY gradlew gradlew.bat /app/
COPY gradle /app/gradle
COPY build.gradle settings.gradle gradle.properties* /app/

RUN chmod +x /app/gradlew


EXPOSE 8080

CMD ["sh", "-c", "chmod +x /app/gradlew 2>/dev/null || true && ./gradlew bootRun --continuous --no-daemon"]